spring.application.name=HabitApp

spring.datasource.url=jdbc:postgresql://localhost:5432/habitapp
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true